USE [QLDSV_HTC]
GO

/****** Object:  View [dbo].[Get_DSLop]    Script Date: 24/11/2021 22:36:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[Get_DSMH]
AS
SELECT MAMH, TENMH, SOTC, SOTIET
FROM     dbo.MONHOC
GO